Controllers/ChuDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;

namespace WebSiteBanSach.Controllers
{
    public class ChuDeController : Controller
    {
        //
        // GET: /ChuDe/
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        public ActionResult ChuDePartial()
        {

            return PartialView(db.ChuDes.Take(5).ToList());
        }
        //Sách theo chủ đề
        public ViewResult SachTheoChuDe(int MaChuDe=0)
        { 
            //Kiểm tra chủ đề tồn tại hay không
            ChuDe cd = db.ChuDes.SingleOrDefault(n => n.MaChuDe == MaChuDe);
            if(cd==null)
            {
                Response.StatusCode=404;
                return null;
            }
            //Truy xuất danh sách các quyển sách theo chủ đề
            List<Sach> lstSach = db.Saches.Where(n=>n.MaChuDe==MaChuDe).OrderBy(n=>n.GiaBan).ToList();
            if(lstSach.Count==0)
            {
                ViewBag.Sach="Không có sách nào thuộc chủ đề này";
            }
            //Gán danh sách chủ để
            ViewBag.lstChuDe = db.ChuDes.ToList();
            return View(lstSach);
        }
        //Hiển thị các chủ đề và sách theo chủ đề đầu tiên
        public ViewResult DanhMucChuDe()
        {
            //Lấy ra chủ đề đầu tiên trong csdl
            int MaChuDe = int.Parse(db.ChuDes.ToList().ElementAt(0).MaChuDe.ToString());
            //Tạo 1 viewbag gán sách theo chủ đề đầu tiên trong csdl
            ViewBag.SachTheoChuDe = db.Saches.Where(n => n.MaChuDe == MaChuDe).ToList() ;
            return View(db.ChuDes.ToList());
        }
	}
}

Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;

namespace WebSiteBanSach.Controllers
{
    public class NguoiDungController : Controller
    {

        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        // GET: /NguoiDung/
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DangKy()
        {

            return View();
        }
        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult DangKy(KhachHang kh)
        {
            if (ModelState.IsValid)
            {
                //Chèn dữ liệu vào bảng khách hàng
                db.KhachHangs.Add(kh);
                //Lưu vào csdl 
                db.SaveChanges();
            }
            return View();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {

            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            string sTaiKhoan = f["txtTaiKhoan"].ToString();
            string sMatKhau = f.Get("txtMatKhau").ToString();
            KhachHang kh = db.KhachHangs.SingleOrDefault(n => n.TaiKhoan == sTaiKhoan && n.MatKhau == sMatKhau);
            if (kh != null)
            {
                ViewBag.ThongBao = "Chúc mừng bạn đăng nhập thành công !";
                Session["TaiKhoan"] = kh;
                return View();
            }
            ViewBag.ThongBao = "Tên tài khoản hoặc mật khẩu không đúng!";
            return View();
        }
	}
}

Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;

namespace WebSiteBanSach.Controllers
{
    public class SachController : Controller
    {
        //
        // GET: /SachMoiPartial/
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        public PartialViewResult SachMoiPartial()
        {
            var lstSachMoi = db.Saches.Take(3).ToList();
            return PartialView(lstSachMoi);
        }
        //Xem chi tiết
        public ViewResult XemChiTiet(int MaSach=0)
        {
            Sach sach = db.Saches.SingleOrDefault(n=>n.MaSach==MaSach);
            if (sach == null)
            { 
                //Trả về trang báo lỗi 
                Response.StatusCode = 404;
                return null;
            }
            //ChuDe cd = db.ChuDes.Single(n => n.MaChuDe == sach.MaChuDe);
            //ViewBag.TenCD = cd.TenChuDe;
            ViewBag.TenChuDe = db.ChuDes.Single(n => n.MaChuDe == sach.MaChuDe).TenChuDe;
            ViewBag.NhaXuatBan = db.NhaXuatBans.Single(n => n.MaNXB == sach.MaNXB).TenNXB;
            return View(sach);
        }
	}
}

Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;
using PagedList.Mvc;
using PagedList;
namespace WebSiteBanSach.Controllers
{
    public class TimKiemController : Controller
    {
        //
        // GET: /TimKiem/
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f,int? page)
        {
            string sTuKhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            List<Sach> lstKQTK = db.Saches.Where(n => n.TenSach.Contains(sTuKhoa)).ToList();
            //Phân trang
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào";
                return View(db.Saches.OrderBy(n => n.TenSach).ToPagedList(pageNumber,pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n=>n.TenSach).ToPagedList(pageNumber,pageSize));
        }
        [HttpGet]
        public ActionResult KetQuaTimKiem(int? page,string sTuKhoa)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<Sach> lstKQTK = db.Saches.Where(n => n.TenSach.Contains(sTuKhoa)).ToList();
            //Phân trang
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy sản phẩm nào";
                return View(db.Saches.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }
	}
}

Views/Layout/NguoiDungLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*Chèn link css của free template download *@
    <link href="~/Content/NguoiDungCssLayout/fonts.css" rel="stylesheet" />
    <link href="~/Content/NguoiDungCssLayout/screen.css" rel="stylesheet" />
    @*Chèn css thiết kế *@
    <link href="~/Content/NguoiDungCssLayout/NguoiDungCssLayout.css" rel="stylesheet" />
    @*Chèn css font ký tự *@
    <link href="~/Content/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet" />
    @*Chèn link nivo slider*@
    <link href="~/NivoSlider/nivo-slider.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/NivoSlider/jquery.nivo.slider.js"></script>
    <script src="~/NivoSlider/jquery.nivo.slider.pack.js"></script>
</head>

<body>
    <div id="ToanTrang">
        <section class="blank">
            <div class="flash">
                <div class="icDienThoai">
                    <i class="fa fa-phone"></i>
                    (08) 1900-1560
                </div>
                @*Tạo div đăng ký đăng nhập*@
                <div class="DangKyDangNhap">
                    @Html.Action("GioHangPartial","GioHang")
                    <i class="fa fa-sign-in"></i>
                    @Html.ActionLink("Đăng ký", "DangKy","NguoiDung", null, htmlAttributes: new { @class = "DangKy" })
                    <i class="fa fa-unlock"></i>
                    @Html.ActionLink("Đăng nhập", "DangNhap","NguoiDung", null, htmlAttributes: new { @class = "DangNhap" })

                </div>
            </div>

            @*Xây dựng div menu header*@

            <div style="background-color: #426db5" class="flash success" id="divDanhMuc">
                @*Hộp thoại tìm kiếm*@
                <div id="txtTimKiem">
                    @using (Html.BeginForm("KetQuaTimKiem","TimKiem",FormMethod.Post))
                    {
                        @Html.TextBox("txtTimKiem", "", htmlAttributes: new { @class = "TextBoxTimKiem", @placeholder = "Nhập vào từ khóa cần tìm ..." })
                        @*Chèn vào image button hình ảnh*@
                        <div id="divHinhAnhTimKiem">
                            <button type="submit"><img src="~/HinhAnh/imgSearch.png" /> </button>
                        </div>
                    }

                </div>
                @*Menu bên phải header*@
                <ul class="navMenu">
                    <li>
                        <a href="@Url.Action("Index","Home")">Trang chủ</a>
                    </li>
                    <li>
                        <a href="#">Giới thiệu</a>
                    <li>
                        <a href="#">Liên hệ</a>
                    </li>
                    <li>
                        <a href="#">Hướng dẫn</a>
                    </li>
                    <li>
                        <a href="#">Sách</a>
                    </li>


                </ul>
            </div>
        </section>

        <section id="divMenuSlider">
            @*Div menu bên trái *@
            <div id="divMenuLeft">
                @*Chèn vào partial view sách mới*@
                <div class="activity">
                    @Html.Action("SachMoiPartial", "Sach")

                </div>
            </div>
            @*Chèn div nivoslider*@
            <div id="slider" class="nivoSlider">
                <img src="~/HinhAnh/Anh1.png" />
                <img src="~/HinhAnh/Anh2.png" />
                <img src="~/HinhAnh/Anh3.png" />
            </div>
            <div style="clear:both"></div>
        </section>
        @*Div body *@
        <div id="NoiDung">
            @RenderBody()

        </div>
        <div id="divChuDeVaNXB">
            <section>
                @*Phần chủ đề*@
                <div id="divChuDe">
                    @Html.Action("ChuDePartial", "ChuDe")

                </div>
                <hr>




            </section>
            <div style="clear:both"></div>
            @*Div nhà xuất bản*@
            <section class="blank items">
                <div id="divLeft">
                    <div class="item">
                        <div class="item-info" id="divNhaXuatBan">
                            @*Action partialview*@
                            @Html.Action("NhaXuatBanPartial", "NhaXuatBan")

                        </div>
                        <img src="http://lorempixel.com/400/300/" alt="Image">
                    </div>
                </div>
                <div id="divRight">
                    @RenderSection("NoiDungBenPhai", false)
                </div>
            </section>
        </div>
        <div style="clear:both"></div>
        <div>
            <a href="#" class="button button-buy">Chào mừng các bạn đã đến với khóa học trực tuyến MyClass.VN</a>
        </div>


       
    </div>
    
    @*Script Chạy nivoslider*@
    <script type="text/javascript">
        $(window).load(function () {
            $('#slider').nivoSlider({
                controlNav: false,               // 1,2,3... navigation
                nextText: '',
                prevText:''
            });
        });
    </script>
</body>

</html>