Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSiteBanSach.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;
namespace WebSiteBanSach.Controllers
{
    public class QuanLySanPhamController : Controller
    {
        //
        // GET: /QuanLySanPham/
        QuanLyBanSachEntities db = new QuanLyBanSachEntities();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(db.Saches.ToList().OrderBy(n=>n.MaSach).ToPagedList(pageNumber,pageSize));
        }
        //Thêm mới 
        [HttpGet]
        public ActionResult ThemMoi()
        {
            //Đưa dữ liệu vào dropdownlist
            ViewBag.MaChuDe = new SelectList( db.ChuDes.ToList().OrderBy(n=>n.TenChuDe),"MaChuDe","TenChuDe");
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n=>n.TenNXB), "MaNXB", "TenNXB"); ;
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(Sach sach, HttpPostedFileBase fileUpload)
        {

                
                //Đưa dữ liệu vào dropdownlist
                ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe");
                ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB");
                //kiểm tra đường dẫn ảnh bìa
                if (fileUpload == null)
                {
                    ViewBag.ThongBao = "Chọn hình ảnh";
                    return View();
                }
                //Thêm vào cơ sở dữ liệu
                if (ModelState.IsValid)
                {
                    //Lưu tên file
                    var fileName = Path.GetFileName(fileUpload.FileName);
                    //Lưu đường dẫn của file
                    var path = Path.Combine(Server.MapPath("~/HinhAnhSP"), fileName);
                    //Kiểm tra hình ảnh đã tồn tại chưa
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                    }
                    else
                    {
                        fileUpload.SaveAs(path);
                    }
                    sach.AnhBia = fileUpload.FileName;
                    db.Saches.Add(sach);
                    db.SaveChanges();
                }
                return View();
        }
        //Chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult ChinhSua(int MaSach)
        {
            //Lấy ra đối tượng sách theo mã 
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Đưa dữ liệu vào dropdownlist
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe",sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB",sach.MaNXB);
            return View(sach);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(Sach sach,FormCollection f)
        {
            //Sach sach1 = db.Saches.SingleOrDefault(n => n.MaSach == sach.MaSach);
            //sach1.MoTa = sach.MoTa;
            //sach1.MoTa = f.Get("abc").ToString();
            //sach.MoTa = f["abc"].ToString();
            //db.SaveChanges();

          
          
            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhận trong model
                db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            //Đưa dữ liệu vào dropdownlist
            ViewBag.MaChuDe = new SelectList(db.ChuDes.ToList().OrderBy(n => n.TenChuDe), "MaChuDe", "TenChuDe", sach.MaChuDe);
            ViewBag.MaNXB = new SelectList(db.NhaXuatBans.ToList().OrderBy(n => n.TenNXB), "MaNXB", "TenNXB", sach.MaNXB);

            return RedirectToAction("Index");
        
        }
        //Hiển thị sản phẩm
        public ActionResult HienThi(int MaSach)
        {

            //Lấy ra đối tượng sách theo mã 
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
          
            return View(sach);
        
        }
        //Xóa sản phẩm
        [HttpGet]
        public ActionResult Xoa(int MaSach)
        {
            //Lấy ra đối tượng sách theo mã 
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            return View(sach);
        }
        [HttpPost,ActionName("Xoa")]

        public ActionResult XacNhanXoa(int MaSach)
        {
            Sach sach = db.Saches.SingleOrDefault(n => n.MaSach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        
        }
	}
}

Views/QuanLySanPham/ChinhSua.cshtml
@model WebSiteBanSach.Models.Sach

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Chỉnh sửa sách</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sach</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.MaSach, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span style="font-size:15pt;margin-top:2px;margin-left:5px">@Model.MaSach</span>
                @Html.Hidden("MaSach",Model.MaSach)
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach)
                @Html.ValidationMessageFor(model => model.TenSach)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan)
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

       
        @Html.TextBox("abc","abc")
        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NgayCapNhat)
                @Html.ValidationMessageFor(model => model.NgayCapNhat)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhBia)
                @Html.ValidationMessageFor(model => model.AnhBia)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon)
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe")

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNXB, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNXB")

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Moi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Moi)
                @Html.ValidationMessageFor(model => model.Moi)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="MoTa">@Model.MoTa</textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>

     
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/QuanLySanPham/HienThi.cshtml
@model WebSiteBanSach.Models.Sach

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>HienThi</h2>

<div>
    <h4>Sach</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.Raw(Model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhBia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuDe.TenChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuDe.TenChuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaXuatBan.TenNXB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaXuatBan.TenNXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaSach=Model.MaSach }) |
    @Html.ActionLink("Trở về", "Index")
</p>

Views/QuanLySanPham/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<WebSiteBanSach.Models.Sach>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Thêm mới sách", "ThemMoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenSach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgayCapNhat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().AnhBia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().SoLuongTon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaChuDe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaNXB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Moi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenSach)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiaBan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MoTa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayCapNhat)
        </td>
        <td>
    <div id="AnhBia"><img src="@Url.Content("~/HinhAnhSP/"+item.AnhBia)" width="10" height="150" /></div>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuongTon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaChuDe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhaXuatBan.TenNXB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Moi)
        </td>
        <td>
            @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaSach=item.MaSach }) |
            @Html.ActionLink("Hiển thị", "HienThi", new { @MaSach = item.MaSach }) |
            @Html.ActionLink("Xoa", "Xoa", new { @MaSach = item.MaSach })
        </td>
    </tr>
}

</table>
@* Tạo link liên kết các trang*@
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

Views/QuanLySanPham/ThemMoi.cshtml
@model WebSiteBanSach.Models.Sach

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>ThemMoi</h2>
@*Thêm thuộc tính cho form để upload ảnh*@
@using (Html.BeginForm("ThemMoi", "QuanLySanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sach</h4>
        <hr />
        @Html.ValidationSummary(true)

       

        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSach)
                @Html.ValidationMessageFor(model => model.TenSach)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan)
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

      

        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayCapNhat)
                @Html.ValidationMessageFor(model => model.NgayCapNhat)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*Name của thẻ input file phải trùng tên với tham số bên controller*@
                <input type="file" name="fileUpload">
                @*Thông báo trùng*@
                @ViewBag.ThongBao
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon)
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaChuDe, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe")

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNXB, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNXB")

            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.Moi, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Moi)
                @Html.ValidationMessageFor(model => model.Moi)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="MoTa">Easy! You should check out MoxieManager!</textarea>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/QuanLySanPham/Xoa.cshtml
@model WebSiteBanSach.Models.Sach

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


<h3>Bạn có thật sự muốn xóa quyển sách này?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhBia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChuDe.TenChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChuDe.TenChuDe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaXuatBan.TenNXB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaXuatBan.TenNXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở về", "Index")
        </div>
    }
</div>